language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "4"
  - "5"
script:
  - ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
after_success:
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info
sudo: false
